AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
